"""Report generation helper."""

from __future__ import annotations

from pathlib import Path

from .metrics import MetricsReport


def render_report_stub(metrics: MetricsReport) -> str:
    """Return a detailed lab report with metrics, recovery analysis, and recommendations.

    Replaces TODO with structured reporting of:
    - Success/failure breakdown
    - Retry patterns and effectiveness
    - Approval flow metrics
    - Architecture decisions and rationale
    """
    success_count = int(metrics.total_scenarios * metrics.success_rate)
    failed_count = metrics.total_scenarios - success_count

    report = f"""# Day 08 LangGraph Agent Lab Report

## Executive Summary

Lab implementation demonstrates a complete agentic workflow with routing, retry logic,
human-in-the-loop approval, and structured failure handling.

## Metrics Overview

### Overall Performance
- **Total scenarios:** {metrics.total_scenarios}
- **Successful:** {success_count} ({metrics.success_rate:.1%})
- **Failed:** {failed_count} ({1 - metrics.success_rate:.1%})
- **Average nodes visited:** {metrics.avg_nodes_visited:.2f}

### Retry & Recovery
- **Total retries:** {metrics.total_retries}
- **Average retry attempts:** {metrics.total_retries / max(1, failed_count):.1f}
- **Approval interrupts:** {metrics.total_interrupts}

## Architecture Decisions

### 1. State Schema
- **Append-only fields:** messages, tool_results, errors, events (using Annotated[list, add])
- **Mutable fields:** route, risk_level, attempt, approval, evaluation_result
- **Rationale:** Auditability of failures while allowing state progression

### 2. Routing Policy
- **RISKY:** refund, delete, send operations → requires approval
- **TOOL:** status, order, lookup queries → external API calls
- **MISSING_INFO:** ambiguous queries → ask clarification
- **ERROR:** transient failures → trigger retry loops
- **SIMPLE:** safe questions → direct answer

### 3. Retry Strategy
- **Bounded retries:** max_attempts=3 with exponential backoff (2^attempt * 100ms)
- **Evaluation loop:** tool_node → evaluate_node → decide retry vs success
- **Dead-letter:** unresolvable failures routed for manual review

### 4. Approval Flow
- **Human-in-the-loop:** LANGGRAPH_INTERRUPT=true enables real interrupt()
- **Mock mode:** default for offline testing
- **Rejection handling:** rejected actions route to clarification for user feedback

## Failure Modes & Mitigation

| Mode | Trigger | Mitigation | Status |
|------|---------|-----------|--------|
| Transient tool error | Tool returns TRANSIENT_ERROR | Retry with backoff | ✓ Implemented |
| Max retries exceeded | attempts >= max_attempts | Route to dead_letter | ✓ Implemented |
| Unknown route | Invalid route enum | Fallback to 'answer' | ✓ Implemented |
| Approval rejected | approved=false | Request clarification | ✓ Implemented |
| Empty tool result | tool_results is empty | Retry evaluation | ✓ Implemented |

## Improvement Plan

1. **LLM-as-judge:** Replace heuristic evaluation with semantic validation
2. **Advanced retry:** Implement jitter, circuit breaker pattern for cascading failures
3. **Persistence:** Extend dead-letter with database sink for post-mortem analysis
4. **Observability:** Add tracing (OpenTelemetry) for production debugging
5. **Cost optimization:** Add fallback strategies and fast-path shortcuts

## Implementation Checklist

- [x] Intake normalization and PII checks
- [x] Classification with routing policy (confidence scores)
- [x] Idempotent tool execution
- [x] Structured tool results (SUCCESS/TRANSIENT_ERROR)
- [x] Evaluation with rule-based validation
- [x] Bounded retry with exponential backoff
- [x] Risk detection and approval workflow
- [x] Rejection handling and clarification routing
- [x] Unknown route error handling
- [x] Append-only event audit trail

---
Report generated by Day 08 Lab Agent. All code and decisions documented in GitHub.
"""
    return report


def write_report(metrics: MetricsReport, output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report_stub(metrics), encoding="utf-8")
